### PR TITLE
Fix intrinsic sizing for rows that contain width-in-height-out layout (e.g., wrapping text)

### LINKED ISSUE #76: Improper intrinsic track sizing for multi-line Text
This widget is extremely powerful and very handy, thank you!

Imagine you have a vertical `CustomScrollView` with a `SliverFillRemaining` sliver (`hasScrollBody`=`false`) that contains a container with a minimum height set to 300px that contains a `LayoutGrid` with a single column and 2 rows:
* A flex row that expands to whatever free space is remaining
* A row that contains a Text that is long enough to wrap across multiple lines

Yes, this is a complicated layout! Essentially, it's a simplified example of an application that has a lot of vertically expanding content that is intrinsically sized, and then needs one row in a grid that is normally sized to fit the rest of the viewport, but if that content is longer than the height of the viewport it will then be able to scroll to see everything.

The bug in this situation is that in the first pass Flutter will call `computeMaxIntrinsicHeight` on the `RenderLayoutGrid` renderbox (because it's in a context where the cross-axis (horizontal) is fixed and it wants to know how high the widget can go for a given width), and flutter passes the fixed cross-axis width. The code is currently specifying a constraint of a minimum width for the given width passed to `_computeIntrinsicSize`: 

```
  @override
  double computeMaxIntrinsicHeight(double width) =>
      _computeIntrinsicSize(BoxConstraints(minWidth: width)).maxTracksHeight;
```

`_computeIntrinsicSize` then calls computeGridSize passing the constraints, but leaving the child constraints set to null. Then the child constraints land up getting inflated to infinity.

This is a problem because when it's computing the row track height, even with a grid fit of passthrough, the childConstraints has a min width of the defined amount but a max width of infinity. The max width of infinity gets translated into a `crossAxisSize=0` when `minIntrinsicSize` is finally called. And because `crossAxisSize=0`, then the Text widget computes a height of like 3000 pixels (exact number depends on how much text is passed) because the Text RenderBox is asked what it's intrinsic height would be with a zero width, and because Text will wrap it creates one line of text per word making it very big. This leads to a very large max intrinsic height of thousands of pixels. Then flutter calls the layout itself, and now it passes the constraint with the height set to 3000+ pixels. The width is now set in this second computation, and the computeGridSize call this time only needs a few lines of text (for example). This leaves the flex row expanding to be thousands of pixels in size unnecessarily.

Here is the debug track layout print output with some extra stuff added showing the problem (in this case there is a single column with 3 rows, row 0 and row 2 are intrinsically sized, and row 2 has the multi-line text widget):

<details>
 <summary>Debug Log Showing Problem</summary>

```
DEBUG: ============= computeMaxIntrinsicHeight(579) =========
DEBUG: ------------------------- computeGridSize(gridFit=GridFit.passthrough, gridConstraints=BoxConstraints(579.0<=w<=Infinity, 0.0<=h<=Infinity), childConstraints=null)
DEBUG: ------------------------- computeGridSize updated childConstraints=BoxConstraints(579.0<=w<=Infinity, 0.0<=h<=Infinity)
DEBUG COLUMN tracks with a maximum free space of 0, isAxisUpperBound=false
min-max: 0.0->0.0 (same)
free space: 0
DEBUG ROW tracks with a maximum free space of 0, isAxisUpperBound=false
Resolving intrinsic row heights [tracks [0,2]] with constraints BoxConstraints(579.0<=w<=Infinity, 0.0<=h<=Infinity)
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=0
  min size of track 0 = 56
  distributing 56 across track 0 on min
  max size of track 0 = 56
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=0
  min size of track 2 = 3902
  distributing 3902 across track 2 on min
  max size of track 2 = 3902
  update track 0 = 56.0
  update track 2 = 3902.0
min-max: 3958.0->3958.0 (same)
free space: -3958
DEBUG ================= Starting grid layout for constraints BoxConstraints(w=579.0, h=3958.0), child constraints BoxConstraints(w=579.0, h=3958.0)
DEBUG: ------------------------- computeGridSize(gridFit=GridFit.passthrough, gridConstraints=BoxConstraints(w=579.0, h=3958.0), childConstraints=null)
DEBUG: ------------------------- computeGridSize updated childConstraints=BoxConstraints(w=579.0, h=3958.0)
DEBUG COLUMN tracks with a maximum free space of 579, isAxisUpperBound=true
min-max: 0.0->0.0 (same)
free space: 579
DEBUG ROW tracks with a maximum free space of 3958, isAxisUpperBound=true
Resolving intrinsic row heights [tracks [0,2]] with constraints BoxConstraints(w=579.0, h=3958.0)
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 0 = 56
  distributing 56 across track 0 on min
  max size of track 0 = 56
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 2 = 94
  distributing 94 across track 2 on min
  max size of track 2 = 94
  update track 0 = 56.0
  update track 2 = 94.0
min-max: 150.0->150.0 (same)
free space: 3808
Determined track sizes:
  column 0: 579
  row 0: 56
  row 1: 3808
  row 2: 94
Finished track sizing
```
</details>

The solution is pretty simple, when computing the max intrinsic width or max intrinsic height, instead of setting a `minHeight` or `minWidth` constraint, set a `maxHeight` or `maxWidth` constraint:

```
  @override
  double computeMaxIntrinsicWidth(double height) =>
      _computeIntrinsicSize(BoxConstraints(maxHeight: height)).maxTracksWidth;

  @override
  double computeMaxIntrinsicHeight(double width) =>
      _computeIntrinsicSize(BoxConstraints(maxWidth: width)).maxTracksHeight;
```

This logic follows by reading the doc comments where it talks about width-in-height-out layout algorithms (e.g., which is what the `Text` widget is with line wrapping).

With this fix in place, the layout works exactly as desired, with no extra space in the flex widget. Here is the debug layout log with the fix in place:

<details>
 <summary>Debug Log With Fix In Place</summary>

```
DEBUG: ============= computeMaxIntrinsicHeight(579) =========
DEBUG: ------------------------- computeGridSize(gridFit=GridFit.passthrough, gridConstraints=BoxConstraints(0.0<=w<=579.0, 0.0<=h<=Infinity), childConstraints=null)
DEBUG: ------------------------- computeGridSize updated childConstraints=BoxConstraints(0.0<=w<=579.0, 0.0<=h<=Infinity)
DEBUG COLUMN tracks with a maximum free space of 579, isAxisUpperBound=true
min-max: 0.0->0.0 (same)
free space: 579
DEBUG ROW tracks with a maximum free space of 0, isAxisUpperBound=false
Resolving intrinsic row heights [tracks [0,2]] with constraints BoxConstraints(0.0<=w<=579.0, 0.0<=h<=Infinity)
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 0 = 56
  distributing 56 across track 0 on min
  max size of track 0 = 56
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 2 = 94
  distributing 94 across track 2 on min
  max size of track 2 = 94
  update track 0 = 56.0
  update track 2 = 94.0
min-max: 150.0->150.0 (same)
free space: -150
DEBUG ================= Starting grid layout for constraints BoxConstraints(w=579.0, h=469.0), child constraints BoxConstraints(w=579.0, h=469.0)
DEBUG: ------------------------- computeGridSize(gridFit=GridFit.passthrough, gridConstraints=BoxConstraints(w=579.0, h=469.0), childConstraints=null)
DEBUG: ------------------------- computeGridSize updated childConstraints=BoxConstraints(w=579.0, h=469.0)
DEBUG COLUMN tracks with a maximum free space of 579, isAxisUpperBound=true
min-max: 0.0->0.0 (same)
free space: 579
DEBUG ROW tracks with a maximum free space of 469, isAxisUpperBound=true
Resolving intrinsic row heights [tracks [0,2]] with constraints BoxConstraints(w=579.0, h=469.0)
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 0 = 56
  distributing 56 across track 0 on min
  max size of track 0 = 56
DEBUG: measuring minIntrinsicSize for 1 items...
DEBUG: measuring min intrinsic item size on axis Axis.vertical with crossAxisSize=579
  min size of track 2 = 94
  distributing 94 across track 2 on min
  max size of track 2 = 94
  update track 0 = 56.0
  update track 2 = 94.0
min-max: 150.0->150.0 (same)
free space: 319
Determined track sizes:
  column 0: 579
  row 0: 56
  row 1: 319
  row 2: 94
Finished track sizing
```
</details>

I'm pretty sure the changes to `computeMaxIntrinsicWidth` and `computeMaxIntrinsicHeight` are correct in all cases, but you could also choose to only use the new behavior based on a new flag to the `LayoutGrid`.

### PR DESCRIPTION
**Pull request by klondikedragon**
Fixes #76.

Tested and verified that all layouts for the example app are correct (no visible differences before/after) after making this change. I believe this new behavior should be desired in all cases, so there is no widget option to change it.

Also make some minor fixes so the scrabble app can run on web on newer flutter versions, and so that the periodic table is redrawn properly on web platform as window resizes.

### CODE REVIEW

File: example/lib/support/inner_shadow.dart [hunk 1]
```diff
@@ -25,11 +25,12 @@ class InnerShadow extends SingleChildRenderObjectWidget {
 
   @override
   RenderInnerShadow createRenderObject(BuildContext context) {
-    return RenderInnerShadow()
-      ..color = color
```
Comment (shyndman) [inline example/lib/support/inner_shadow.dart:29]: Hmm, wonder why I did it like this. Possibly a copy and paste job without much thought.

File: example/lib/periodic_table.dart [hunk 2]
```diff
@@ -31,7 +31,8 @@ class PeriodicTableApp extends StatelessWidget {
         builder: (_, __) {
           return LayoutBuilder(builder: (_, constraints) {
             _viewportSize = constraints.biggest;
-            return const SingleChildScrollView(child: PeriodicTableWidget());
+            // ignore: prefer_const_constructors
```
Comment (shyndman) [inline example/lib/periodic_table.dart:34]: This confused me, so I went in and played with it. You may know all this, but for posterity.

The grid and grid items do re-render on layout changes, but because `AtomicElementWidget.build` relies on a `_viewportSize` variable that is updated on each layout, we need those `build` methods to run repeatedly. The dangers of depending on global state.

There's definitely a more elegant way to do this, but it's example code, so whatever.

Mind adding a comment to describe why we have that ignore there?

File: example/lib/support/inner_shadow.dart (hunk 1 above)
Comment (shyndman) [reply example/lib/support/inner_shadow.dart:29]: Oh, no, I remember why. This is the pattern followed by render objects in the framework, because render objects are longer lived and are updated over time as their widgets/context changes.

They avoid the `late` by having field defaults.

But all good. This change is perfect. Thank you. :)

File: example/lib/periodic_table.dart (hunk 2 above)
Comment (klondikedragon) [reply example/lib/periodic_table.dart:40]: Good point, will be helpful to readers to better understand the example code!

**Comment by klondikedragon** [comment]
@shyndman - see what you think now!

**Comment by shyndman** [comment]
lgtm. 

Thank you!
